import { LAYOUT_IDS, type SkinLayout } from "./layouts/layout-ids";

export type { SkinLayout };
export { LAYOUT_IDS };

export type ThemeTokens = {
  id: string;
  name: string;
  tagline: string;
  layout: SkinLayout;
  /** browser chrome */
  themeColor: string;
  bg: string;
  bg2?: string;
  fg: string;
  muted: string;
  accent: string;
  accent2?: string;
  accentFg: string;
  card: string;
  line: string;
  danger: string;
  font: string;
  displayFont?: string;
  monoFont?: string;
  radius: "sharp" | "soft" | "round" | "pill";
  density: "comfy" | "tight";
  surface: "glass" | "flat" | "raised" | "outline";
  /** optional CSS background shorthand (gradient etc.) */
  wallpaper?: string;
};

/** 80-ish color + layout showcase themes — CSS vars paint; layout drives structure. */
export const THEME_CATALOG: ThemeTokens[] = [
  // —— refined originals (10) ——
  {
    id: "aurora",
    name: "极光",
    tagline: "北境夜空 · 冰蓝柔光",
    layout: "side",
    themeColor: "#0a1628",
    bg: "#0a1628",
    fg: "#eaf2ff",
    muted: "#8ea2c0",
    accent: "#5eead4",
    accent2: "#38bdf8",
    accentFg: "#042f2e",
    card: "rgba(255,255,255,0.07)",
    line: "rgba(94,234,212,0.22)",
    danger: "#fda4af",
    font: '"DM Sans", "PingFang SC", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
      "radial-gradient(ellipse 80% 60% at 15% 0%, #164e63 0%, transparent 55%), radial-gradient(ellipse 70% 50% at 90% 10%, #1e3a8a 0%, transparent 50%), #0a1628",
  },
  {
    id: "midnight",
    name: "午夜",
    tagline: "OLED 纯黑 · 冷静青线",
    layout: "compact",
    themeColor: "#000000",
    bg: "#000000",
    fg: "#f4f4f5",
    muted: "#71717a",
    accent: "#22d3ee",
    accentFg: "#083344",
    card: "#0a0a0a",
    line: "#27272a",
    danger: "#fb7185",
    font: '"Syne", "DM Sans", system-ui, sans-serif',
    monoFont: '"IBM Plex Mono", ui-monospace, monospace',
    radius: "sharp",
    density: "tight",
    surface: "flat",
  },  {
    id: "neon",
    name: "霓虹",
    tagline: "赛博夜色 · 紫青灯牌",
    layout: "immersive",
    themeColor: "#0f0518",
    bg: "#0f0518",
    fg: "#faf5ff",
    muted: "#a78bfa",
    accent: "#e879f9",
    accent2: "#22d3ee",
    accentFg: "#3b0764",
    card: "rgba(15,5,24,0.55)",
    line: "rgba(232,121,249,0.35)",
    danger: "#fb7185",
    font: '"Syne", "DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
      "radial-gradient(circle at 75% 15%, #6b21a8 0%, transparent 42%), radial-gradient(circle at 10% 80%, #0e7490 0%, transparent 40%), #0f0518",
  },
  {
    id: "ocean",
    name: "深海",
    tagline: "远洋靛蓝 · 圆环封面",
    layout: "side",
    themeColor: "#020617",
    bg: "#020617",
    fg: "#e0f2fe",
    muted: "#7dd3fc",
    accent: "#38bdf8",
    accentFg: "#0c4a6e",
    card: "rgba(14,165,233,0.1)",
    line: "rgba(56,189,248,0.28)",
    danger: "#fda4af",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "round",
    density: "comfy",
    surface: "glass",
    wallpaper:
      "radial-gradient(ellipse at 50% 120%, #0c4a6e 0%, transparent 55%), linear-gradient(180deg, #020617, #041525)",
  },
  {
    id: "sakura",
    name: "樱花",
    tagline: "春日柔粉 · 圆润轻盈",
    layout: "side",
    themeColor: "#fff1f2",
    bg: "#fff1f2",
    fg: "#4c0519",
    muted: "#9f1239",
    accent: "#f43f5e",
    accentFg: "#fff",
    card: "#ffffff",
    line: "#fecdd3",
    danger: "#e11d48",
    font: '"DM Sans", "PingFang SC", system-ui, sans-serif',
    radius: "pill",
    density: "comfy",
    surface: "raised",
    wallpaper: "linear-gradient(165deg, #fff1f2 0%, #ffe4e6 45%, #fdf2f8 100%)",
  },
  {
    id: "terminal",
    name: "终端",
    tagline: "CRT 绿字 · 等宽指令",
    layout: "compact",
    themeColor: "#050a05",
    bg: "#050a05",
    fg: "#4ade80",
    muted: "#166534",
    accent: "#86efac",
    accentFg: "#052e16",
    card: "#0a120a",
    line: "#14532d",
    danger: "#f87171",
    font: '"IBM Plex Mono", "SF Mono", ui-monospace, monospace',
    radius: "sharp",
    density: "tight",
    surface: "outline",
  },
  {
    id: "vinyl",
    name: "黑胶",
    tagline: "暖棕复古 · 唱片氛围",
    layout: "immersive",
    themeColor: "#1a120e",
    bg: "#1a120e",
    fg: "#f5e6d3",
    muted: "#a8a29e",
    accent: "#d4a574",
    accentFg: "#1c1410",
    card: "rgba(28,20,16,0.72)",
    line: "rgba(212,165,116,0.32)",
    danger: "#f87171",
    font: '"DM Sans", system-ui, sans-serif',
    displayFont: '"Instrument Serif", Georgia, serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
      "radial-gradient(circle at 30% 20%, #3d2a1f 0%, transparent 45%), #1a120e",
  },
  {
    id: "swiss",
    name: "瑞士",
    tagline: "国际主义 · 红白网格",
    layout: "side",
    themeColor: "#ffffff",
    bg: "#ffffff",
    fg: "#111111",
    muted: "#525252",
    accent: "#dc2626",
    accentFg: "#ffffff",
    card: "#fafafa",
    line: "#111111",
    danger: "#b91c1c",
    font: '"Helvetica Neue", Helvetica, Arial, "PingFang SC", sans-serif',
    radius: "sharp",
    density: "tight",
    surface: "outline",
  },
  {
    id: "sunset",
    name: "落日",
    tagline: "暮色暖橙 · 晚霞渐变",
    layout: "immersive",
    themeColor: "#1c0a05",
    bg: "#1c0a05",
    fg: "#fff7ed",
    muted: "#fdba74",
    accent: "#fb923c",
    accent2: "#f43f5e",
    accentFg: "#1c0a05",
    card: "rgba(67,20,7,0.55)",
    line: "rgba(251,146,60,0.35)",
    danger: "#fb7185",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
      "radial-gradient(ellipse at 50% 100%, #9a3412 0%, transparent 50%), linear-gradient(165deg, #431407, #1c0a05 70%)",
  },

  // —— +30 new styles ——
  {
    id: "noir",
    name: "Noir",
    tagline: "黑白电影 · 高对比",
    layout: "compact",
    themeColor: "#0a0a0a",
    bg: "#0a0a0a",
    fg: "#fafafa",
    muted: "#a3a3a3",
    accent: "#fafafa",
    accentFg: "#0a0a0a",
    card: "#141414",
    line: "#404040",
    danger: "#a3a3a3",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "sharp",
    density: "tight",
    surface: "flat",
  },
  {
    id: "lavender",
    name: "薰衣草",
    tagline: "雾紫柔光 · 安静午后",
    layout: "side",
    themeColor: "#1e1b2e",
    bg: "#1e1b2e",
    fg: "#f3e8ff",
    muted: "#c4b5fd",
    accent: "#c084fc",
    accentFg: "#3b0764",
    card: "rgba(192,132,252,0.1)",
    line: "rgba(192,132,252,0.28)",
    danger: "#f9a8d4",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
      "radial-gradient(ellipse at 20% 0%, #4c1d95 0%, transparent 50%), #1e1b2e",
  }, {
    id: "ember",
    name: "余烬",
    tagline: "暗室炭火 · 深橙余温",
    layout: "immersive",
    themeColor: "#140c0a",
    bg: "#140c0a",
    fg: "#ffedd5",
    muted: "#c2410c",
    accent: "#ea580c",
    accentFg: "#fff7ed",
    card: "rgba(67,20,7,0.5)",
    line: "rgba(234,88,12,0.35)",
    danger: "#f87171",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
      "radial-gradient(circle at 40% 80%, #7c2d12 0%, transparent 45%), #140c0a",
  },
  {
    id: "arctic",
    name: "极地",
    tagline: "冰蓝冷调 · 雪白界面",
    layout: "side",
    themeColor: "#f0f9ff",
    bg: "#f0f9ff",
    fg: "#0c4a6e",
    muted: "#0369a1",
    accent: "#0284c7",
    accentFg: "#f0f9ff",
    card: "#ffffff",
    line: "rgba(2,132,199,0.2)",
    danger: "#e11d48",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "raised",
    wallpaper: "linear-gradient(180deg, #e0f2fe, #f8fafc 60%)",
  },
  {
    id: "grape",
    name: "葡萄",
    tagline: "深紫果香 · 醇厚夜间",
    layout: "side",
    themeColor: "#1a0b24",
    bg: "#1a0b24",
    fg: "#f3e8ff",
    muted: "#d8b4fe",
    accent: "#a855f7",
    accentFg: "#faf5ff",
    card: "rgba(88,28,135,0.35)",
    line: "rgba(168,85,247,0.3)",
    danger: "#f472b6",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "round",
    density: "comfy",
    surface: "glass",
    wallpaper:
      "radial-gradient(ellipse at top, #581c87 0%, #1a0b24 60%)",
  },  {
    id: "matrix",
    name: "矩阵",
    tagline: "数据雨 · 深空绿码",
    layout: "compact",
    themeColor: "#000800",
    bg: "#000800",
    fg: "#00ff66",
    muted: "#008f3a",
    accent: "#39ff14",
    accentFg: "#001a08",
    card: "#001a08",
    line: "#004d20",
    danger: "#ff4d4d",
    font: '"IBM Plex Mono", ui-monospace, monospace',
    radius: "sharp",
    density: "tight",
    surface: "outline",
  },
  {
    id: "rose-gold",
    name: "玫瑰金",
    tagline: "香槟金属 · 轻奢质感",
    layout: "immersive",
    themeColor: "#1c1214",
    bg: "#1c1214",
    fg: "#fdf2f4",
    muted: "#e7b8be",
    accent: "#e8b4b8",
    accent2: "#d4a574",
    accentFg: "#3f1f24",
    card: "rgba(60,30,36,0.55)",
    line: "rgba(232,180,184,0.3)",
    danger: "#fb7185",
    font: '"Syne", "DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
      "linear-gradient(145deg, #2a161a 0%, #1c1214 50%, #241810 100%)",
  },
  {
    id: "blueprint",
    name: "蓝图",
    tagline: "工程图纸 · 精密网格",
    layout: "side",
    themeColor: "#0b1f3a",
    bg: "#0b1f3a",
    fg: "#dbeafe",
    muted: "#60a5fa",
    accent: "#3b82f6",
    accentFg: "#eff6ff",
    card: "rgba(30,58,138,0.35)",
    line: "rgba(96,165,250,0.35)",
    danger: "#f87171",
    font: '"IBM Plex Mono", ui-monospace, monospace',
    radius: "sharp",
    density: "tight",
    surface: "outline",
    wallpaper:
      "linear-gradient(rgba(59,130,246,0.06) 1px, transparent 1px), linear-gradient(90deg, rgba(59,130,246,0.06) 1px, transparent 1px), #0b1f3a",
  },
  {
    id: "honey",
    name: "蜂蜜",
    tagline: "琥珀甜光 · 暖黄日常",
    layout: "immersive",
    themeColor: "#1a1408",
    bg: "#1a1408",
    fg: "#fffbeb",
    muted: "#fbbf24",
    accent: "#f59e0b",
    accentFg: "#1c1408",
    card: "rgba(120,53,15,0.4)",
    line: "rgba(245,158,11,0.35)",
    danger: "#f87171",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "round",
    density: "comfy",
    surface: "glass",
    wallpaper:
      "radial-gradient(ellipse at 30% 0%, #78350f 0%, transparent 50%), #1a1408",
  },
  {
    id: "slate",
    name: "岩灰",
    tagline: "现代中性 · 冷静专业",
    layout: "compact",
    themeColor: "#0f172a",
    bg: "#0f172a",
    fg: "#e2e8f0",
    muted: "#94a3b8",
    accent: "#64748b",
    accentFg: "#f8fafc",
    card: "#1e293b",
    line: "#334155",
    danger: "#f87171",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "flat",
  },
  {
    id: "lime",
    name: "青柠",
    tagline: "酸甜高亮 · 运动活力",
    layout: "side",
    themeColor: "#0a1405",
    bg: "#0a1405",
    fg: "#ecfccb",
    muted: "#a3e635",
    accent: "#a3e635",
    accentFg: "#1a2e05",
    card: "rgba(54,83,20,0.45)",
    line: "rgba(163,230,53,0.35)",
    danger: "#fb7185",
    font: '"Syne", "DM Sans", system-ui, sans-serif',
    radius: "pill",
    density: "comfy",
    surface: "raised",
    wallpaper:
      "radial-gradient(circle at 80% 20%, #3f6212 0%, transparent 40%), #0a1405",
  },
  {
    id: "copper",
    name: "红铜",
    tagline: "工业金属 · 铜色高光",
    layout: "immersive",
    themeColor: "#1a100c",
    bg: "#1a100c",
    fg: "#fde8d8",
    muted: "#c27a4a",
    accent: "#c05621",
    accentFg: "#fff7ed",
    card: "rgba(60,30,15,0.55)",
    line: "rgba(192,86,33,0.4)",
    danger: "#f87171",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
  },
  {
    id: "cloud",
    name: "云朵",
    tagline: "浅灰天空 · 干净轻盈",
    layout: "side",
    themeColor: "#f8fafc",
    bg: "#f8fafc",
    fg: "#0f172a",
    muted: "#64748b",
    accent: "#0ea5e9",
    accentFg: "#f0f9ff",
    card: "#ffffff",
    line: "rgba(15,23,42,0.1)",
    danger: "#e11d48",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "raised",
  },
  {
    id: "vivid",
    name: "原色",
    tagline: "孟菲斯 · 撞色几何",
    layout: "immersive",
    themeColor: "#111827",
    bg: "#111827",
    fg: "#f9fafb",
    muted: "#9ca3af",
    accent: "#fbbf24",
    accent2: "#ec4899",
    accentFg: "#111827",
    card: "#1f2937",
    line: "rgba(251,191,36,0.4)",
    danger: "#f472b6",
    font: '"Syne", "DM Sans", system-ui, sans-serif',
    radius: "sharp",
    density: "comfy",
    surface: "raised",
  },
  {
    id: "forest",
    name: "密林",
    tagline: "苔藓深绿 · 林间静谧",
    layout: "side",
    themeColor: "#0c140f",
    bg: "#0c140f",
    fg: "#dcfce7",
    muted: "#86efac",
    accent: "#22c55e",
    accentFg: "#052e16",
    card: "rgba(20,83,45,0.4)",
    line: "rgba(34,197,94,0.3)",
    danger: "#f87171",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
      "radial-gradient(ellipse at 10% 90%, #14532d 0%, transparent 45%), #0c140f",
  },  {
    id: "pulse",
    name: "脉冲",
    tagline: "电音品红 · 夜场律动",
    layout: "immersive",
    themeColor: "#120014",
    bg: "#120014",
    fg: "#fce7f3",
    muted: "#f9a8d4",
    accent: "#ec4899",
    accent2: "#8b5cf6",
    accentFg: "#500724",
    card: "rgba(80,7,36,0.45)",
    line: "rgba(236,72,153,0.4)",
    danger: "#f472b6",
    font: '"Syne", system-ui, sans-serif',
    radius: "round",
    density: "comfy",
    surface: "glass",
    wallpaper:
      "radial-gradient(circle at 70% 30%, #9d174d 0%, transparent 40%), #120014",
  },
  {
    id: "mono-blue",
    name: "单蓝",
    tagline: "克莱因蓝 · 大胆色块",
    layout: "compact",
    themeColor: "#002fa7",
    bg: "#002fa7",
    fg: "#ffffff",
    muted: "#93c5fd",
    accent: "#ffffff",
    accentFg: "#002fa7",
    card: "rgba(0,0,0,0.15)",
    line: "rgba(255,255,255,0.35)",
    danger: "#fecaca",
    font: '"Helvetica Neue", Helvetica, Arial, sans-serif',
    radius: "sharp",
    density: "tight",
    surface: "flat",
  },
  {
    id: "mocha",
    name: "摩卡",
    tagline: "咖啡厅 · 棕调舒适",
    layout: "side",
    themeColor: "#211710",
    bg: "#211710",
    fg: "#f5e6d3",
    muted: "#c4a484",
    accent: "#a67c52",
    accentFg: "#1c1410",
    card: "rgba(60,40,28,0.6)",
    line: "rgba(166,124,82,0.35)",
    danger: "#f87171",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
  },
  {
    id: "ice",
    name: "冰晶",
    tagline: "冷玻璃 · 透明质感",
    layout: "side",
    themeColor: "#0c1222",
    bg: "#0c1222",
    fg: "#e2e8f0",
    muted: "#94a3b8",
    accent: "#a5f3fc",
    accentFg: "#083344",
    card: "rgba(255,255,255,0.06)",
    line: "rgba(165,243,252,0.25)",
    danger: "#fda4af",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
      "linear-gradient(160deg, #0f172a 0%, #0c1222 50%, #082f49 100%)",
  },
  {
    id: "crimson",
    name: "绯红",
    tagline: "剧院红黑 · 戏剧张力",
    layout: "immersive",
    themeColor: "#140000",
    bg: "#140000",
    fg: "#fee2e2",
    muted: "#fca5a5",
    accent: "#dc2626",
    accentFg: "#fff",
    card: "rgba(60,0,0,0.55)",
    line: "rgba(220,38,38,0.4)",
    danger: "#f87171",
    font: '"Instrument Serif", Georgia, serif',
    displayFont: '"Instrument Serif", Georgia, serif',
    radius: "sharp",
    density: "comfy",
    surface: "outline",
  },
  {
    id: "moss",
    name: "苔原",
    tagline: "北欧绿灰 · 克制自然",
    layout: "compact",
    themeColor: "#141a16",
    bg: "#141a16",
    fg: "#e7ebe4",
    muted: "#8fa38a",
    accent: "#6b8f71",
    accentFg: "#0f1411",
    card: "#1c241e",
    line: "rgba(107,143,113,0.35)",
    danger: "#e07a5f",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "flat",
  },
  {
    id: "candy",
    name: "糖果",
    tagline: "粉蓝撞色 · 俏皮轻快",
    layout: "immersive",
    themeColor: "#fff0f6",
    bg: "#fff0f6",
    fg: "#4a1942",
    muted: "#c26ba0",
    accent: "#ff6bcb",
    accent2: "#70d6ff",
    accentFg: "#fff",
    card: "#ffffff",
    line: "rgba(255,107,203,0.3)",
    danger: "#e11d48",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "pill",
    density: "comfy",
    surface: "raised",
    wallpaper: "linear-gradient(160deg, #fff0f6, #e0f7ff 100%)",
  },
  {
    id: "steel",
    name: "钢青",
    tagline: "冷金属 · 工业蓝灰",
    layout: "side",
    themeColor: "#12151a",
    bg: "#12151a",
    fg: "#e8eef5",
    muted: "#8b9bb0",
    accent: "#7c9cbf",
    accentFg: "#0b1220",
    card: "#1a1f27",
    line: "rgba(124,156,191,0.3)",
    danger: "#f87171",
    font: '"IBM Plex Mono", ui-monospace, monospace',
    radius: "sharp",
    density: "tight",
    surface: "flat",
  },
  {
    id: "peach",
    name: "蜜桃",
    tagline: "晨光蜜橙 · 温柔提亮",
    layout: "split",
    themeColor: "#fff5f0",
    bg: "#fff5f0",
    fg: "#4a2c20",
    muted: "#c47b5a",
    accent: "#ff8a65",
    accentFg: "#fff",
    card: "#ffffff",
    line: "rgba(255,138,101,0.28)",
    danger: "#e11d48",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "round",
    density: "comfy",
    surface: "raised",
  },
  {
    id: "cosmos",
    name: "星河",
    tagline: "深紫太空 · 星尘微光",
    layout: "immersive",
    themeColor: "#070714",
    bg: "#070714",
    fg: "#e0e7ff",
    muted: "#a5b4fc",
    accent: "#818cf8",
    accent2: "#c084fc",
    accentFg: "#1e1b4b",
    card: "rgba(30,27,75,0.55)",
    line: "rgba(129,140,248,0.35)",
    danger: "#f9a8d4",
    font: '"Syne", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
      "radial-gradient(ellipse at 20% 30%, #312e81 0%, transparent 40%), radial-gradient(ellipse at 80% 70%, #4c1d95 0%, transparent 35%), #070714",
  },  {
    id: "volt",
    name: "伏特",
    tagline: "黑底电黄 · 警示高能",
    layout: "compact",
    themeColor: "#0a0a0a",
    bg: "#0a0a0a",
    fg: "#fafafa",
    muted: "#a3a3a3",
    accent: "#facc15",
    accentFg: "#0a0a0a",
    card: "#141414",
    line: "rgba(250,204,21,0.45)",
    danger: "#f87171",
    font: '"Syne", system-ui, sans-serif',
    radius: "sharp",
    density: "tight",
    surface: "outline",
  },

  // —— batch 2026-08 · 35 more distinct palettes ——
  {
    id: "magma",
    name: "岩浆",
    tagline: "地火赤橙 · 炽热压迫",
    layout: "immersive",
    themeColor: "#1a0502",
    bg: "#1a0502",
    fg: "#fff7ed",
    muted: "#fdba74",
    accent: "#f97316",
    accent2: "#ef4444",
    accentFg: "#431407",
    card: "rgba(249,115,22,0.12)",
    line: "rgba(251,146,60,0.35)",
    danger: "#fca5a5",
    font: '"Outfit", "DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
      "radial-gradient(ellipse at 50% 100%, #7c2d12 0%, transparent 50%), radial-gradient(circle at 20% 20%, #9a3412 0%, transparent 40%), #1a0502",
  },
  {
    id: "glacier",
    name: "冰川",
    tagline: "极地雪白 · 冷冽青蓝",
    layout: "split",
    themeColor: "#f0f9ff",
    bg: "#f0f9ff",
    fg: "#0c4a6e",
    muted: "#0284c7",
    accent: "#0ea5e9",
    accentFg: "#f0f9ff",
    card: "#ffffff",
    line: "rgba(14,165,233,0.22)",
    danger: "#e11d48",
    font: '"Outfit", system-ui, sans-serif',
    radius: "round",
    density: "comfy",
    surface: "raised",
    wallpaper: "linear-gradient(165deg, #e0f2fe 0%, #f8fafc 45%, #f0f9ff 100%)",
  },
  {
    id: "jade",
    name: "翠玉",
    tagline: "墨绿奢石 · 金边点缀",
    layout: "side",
    themeColor: "#022c22",
    bg: "#022c22",
    fg: "#ecfdf5",
    muted: "#6ee7b7",
    accent: "#d4af37",
    accent2: "#34d399",
    accentFg: "#14532d",
    card: "rgba(16,185,129,0.12)",
    line: "rgba(212,175,55,0.35)",
    danger: "#fb7185",
    font: '"Playfair Display", "Songti SC", Georgia, serif',
    displayFont: '"Playfair Display", Georgia, serif',
    radius: "soft",
    density: "comfy",
    surface: "raised",
    wallpaper:
      "radial-gradient(ellipse at 80% 0%, #065f46 0%, transparent 50%), #022c22",
  },
  {
    id: "amethyst",
    name: "紫晶",
    tagline: "宝石紫雾 · 柔光玻璃",
    layout: "side",
    themeColor: "#1e1033",
    bg: "#1e1033",
    fg: "#f5f3ff",
    muted: "#c4b5fd",
    accent: "#a78bfa",
    accent2: "#e879f9",
    accentFg: "#2e1065",
    card: "rgba(167,139,250,0.12)",
    line: "rgba(196,181,253,0.28)",
    danger: "#fb7185",
    font: '"Space Grotesk", system-ui, sans-serif',
    radius: "round",
    density: "comfy",
    surface: "glass",
    wallpaper:
      "radial-gradient(circle at 30% 20%, #5b21b6 0%, transparent 45%), radial-gradient(circle at 90% 80%, #86198f 0%, transparent 40%), #1e1033",
  },
  {
    id: "citrus",
    name: "柑橘",
    tagline: "柠檬青绿 · 夏日清爽",
    layout: "compact",
    themeColor: "#f7fee7",
    bg: "#f7fee7",
    fg: "#365314",
    muted: "#65a30d",
    accent: "#84cc16",
    accent2: "#eab308",
    accentFg: "#1a2e05",
    card: "#ffffff",
    line: "rgba(132,204,22,0.35)",
    danger: "#dc2626",
    font: '"Outfit", system-ui, sans-serif',
    radius: "pill",
    density: "tight",
    surface: "flat",
  },
  {
    id: "espresso",
    name: "浓缩",
    tagline: "咖啡深棕 · 奶油点缀",
    layout: "side",
    themeColor: "#1c1410",
    bg: "#1c1410",
    fg: "#faf6f1",
    muted: "#c4a484",
    accent: "#d6a77a",
    accentFg: "#3b2314",
    card: "#2a1f18",
    line: "rgba(214,167,122,0.28)",
    danger: "#f87171",
    font: '"Instrument Serif", Georgia, serif',
    displayFont: '"Instrument Serif", Georgia, serif',
    radius: "soft",
    density: "comfy",
    surface: "raised",
    wallpaper: "linear-gradient(180deg, #2a1f18 0%, #1c1410 100%)",
  },
  {
    id: "flamingo",
    name: "火烈鸟",
    tagline: "珊瑚粉橘 · 度假风情",
    layout: "immersive",
    themeColor: "#fff1f2",
    bg: "#fff1f2",
    fg: "#9f1239",
    muted: "#fb7185",
    accent: "#fb7185",
    accent2: "#fdba74",
    accentFg: "#fff",
    card: "#ffffff",
    line: "rgba(251,113,133,0.3)",
    danger: "#be123c",
    font: '"Syne", system-ui, sans-serif',
    radius: "pill",
    density: "comfy",
    surface: "raised",
    wallpaper:
      "radial-gradient(ellipse at 10% 0%, #fecdd3 0%, transparent 50%), radial-gradient(ellipse at 100% 100%, #fed7aa 0%, transparent 45%), #fff1f2",
  },
  {
    id: "graphite",
    name: "石墨",
    tagline: "工业灰阶 · 冷硬线条",
    layout: "compact",
    themeColor: "#18181b",
    bg: "#18181b",
    fg: "#fafafa",
    muted: "#a1a1aa",
    accent: "#e4e4e7",
    accentFg: "#18181b",
    card: "#27272a",
    line: "#3f3f46",
    danger: "#f43f5e",
    font: '"Space Grotesk", system-ui, sans-serif',
    monoFont: '"JetBrains Mono", monospace',
    radius: "sharp",
    density: "tight",
    surface: "flat",
  },
  {
    id: "mint-ice",
    name: "薄荷冰",
    tagline: "浅薄荷 · 诊所清新",
    layout: "immersive",
    themeColor: "#f0fdfa",
    bg: "#f0fdfa",
    fg: "#134e4a",
    muted: "#0d9488",
    accent: "#14b8a6",
    accentFg: "#f0fdfa",
    card: "#ffffff",
    line: "rgba(20,184,166,0.25)",
    danger: "#e11d48",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "round",
    density: "comfy",
    surface: "flat",
  },
  {
    id: "burgundy",
    name: "勃艮第",
    tagline: "酒红丝绒 · 剧院夜晚",
    layout: "split",
    themeColor: "#2a0a14",
    bg: "#2a0a14",
    fg: "#fce7f3",
    muted: "#f9a8d4",
    accent: "#e11d48",
    accent2: "#fbbf24",
    accentFg: "#fff1f2",
    card: "rgba(225,29,72,0.14)",
    line: "rgba(244,114,182,0.3)",
    danger: "#fda4af",
    font: '"Playfair Display", Georgia, serif',
    displayFont: '"Playfair Display", Georgia, serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
      "radial-gradient(ellipse at 50% 0%, #881337 0%, transparent 55%), #2a0a14",
  },
  {
    id: "cobalt",
    name: "钴蓝",
    tagline: "电气蓝 · 未来面板",
    layout: "side",
    themeColor: "#020617",
    bg: "#020617",
    fg: "#dbeafe",
    muted: "#60a5fa",
    accent: "#2563eb",
    accent2: "#22d3ee",
    accentFg: "#eff6ff",
    card: "rgba(37,99,235,0.15)",
    line: "rgba(96,165,250,0.35)",
    danger: "#fb7185",
    font: '"Space Grotesk", system-ui, sans-serif',
    radius: "sharp",
    density: "tight",
    surface: "outline",
    wallpaper:
      "linear-gradient(135deg, #020617 0%, #0f172a 40%, #1e3a8a 100%)",
  },
  {
    id: "saffron",
    name: "藏红花",
    tagline: "金黄香料 · 南亚暖调",
    layout: "immersive",
    themeColor: "#431407",
    bg: "#431407",
    fg: "#fffbeb",
    muted: "#fcd34d",
    accent: "#f59e0b",
    accent2: "#f97316",
    accentFg: "#451a03",
    card: "rgba(245,158,11,0.14)",
    line: "rgba(252,211,77,0.35)",
    danger: "#fca5a5",
    font: '"Outfit", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "raised",
    wallpaper:
      "radial-gradient(circle at 70% 30%, #b45309 0%, transparent 45%), #431407",
  },
  {
    id: "shadow",
    name: "暗影",
    tagline: "深紫黑雾 · 低调神秘",
    layout: "compact",
    themeColor: "#0c0a12",
    bg: "#0c0a12",
    fg: "#e2e0ea",
    muted: "#8b87a0",
    accent: "#7c3aed",
    accentFg: "#ede9fe",
    card: "#16131f",
    line: "rgba(124,58,237,0.35)",
    danger: "#f472b6",
    font: '"Syne", system-ui, sans-serif',
    radius: "sharp",
    density: "tight",
    surface: "flat",
  },  {
    id: "laser",
    name: "镭射",
    tagline: "黑客绿光 · 终端矩阵",
    layout: "side",
    themeColor: "#020b06",
    bg: "#020b06",
    fg: "#bbf7d0",
    muted: "#4ade80",
    accent: "#22c55e",
    accentFg: "#052e16",
    card: "rgba(34,197,94,0.08)",
    line: "rgba(74,222,128,0.4)",
    danger: "#f87171",
    font: '"JetBrains Mono", "IBM Plex Mono", monospace',
    monoFont: '"JetBrains Mono", monospace',
    radius: "sharp",
    density: "tight",
    surface: "outline",
    wallpaper:
      "repeating-linear-gradient(0deg, transparent, transparent 2px, rgba(34,197,94,0.03) 2px, rgba(34,197,94,0.03) 4px), #020b06",
  },
  {
    id: "coral-reef",
    name: "珊瑚礁",
    tagline: "热带浅滩 · 青绿粉浪",
    layout: "side",
    themeColor: "#042f2e",
    bg: "#042f2e",
    fg: "#ccfbf1",
    muted: "#5eead4",
    accent: "#2dd4bf",
    accent2: "#fb7185",
    accentFg: "#134e4a",
    card: "rgba(45,212,191,0.12)",
    line: "rgba(94,234,212,0.3)",
    danger: "#fda4af",
    font: '"Outfit", system-ui, sans-serif',
    radius: "round",
    density: "comfy",
    surface: "glass",
    wallpaper:
      "radial-gradient(ellipse at 0% 100%, #0f766e 0%, transparent 50%), radial-gradient(circle at 100% 0%, #9d174d 0%, transparent 35%), #042f2e",
  },
  {
    id: "plum",
    name: "梅子",
    tagline: "深梅紫 · 秋日果香",
    layout: "immersive",
    themeColor: "#1a0b16",
    bg: "#1a0b16",
    fg: "#fce7f3",
    muted: "#e9a8cd",
    accent: "#c026d3",
    accent2: "#db2777",
    accentFg: "#fdf4ff",
    card: "rgba(192,38,211,0.14)",
    line: "rgba(232,121,249,0.3)",
    danger: "#fb7185",
    font: '"Playfair Display", Georgia, serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
      "radial-gradient(circle at 20% 80%, #701a75 0%, transparent 45%), #1a0b16",
  },
  {
    id: "chalk",
    name: "黑板",
    tagline: "教室深绿 · 粉笔白字",
    layout: "compact",
    themeColor: "#1a2e1a",
    bg: "#1a2e1a",
    fg: "#f4f4f0",
    muted: "#a3b18a",
    accent: "#e8e6d9",
    accentFg: "#1a2e1a",
    card: "#243524",
    line: "rgba(232,230,217,0.25)",
    danger: "#fca5a5",
    font: '"IBM Plex Mono", monospace',
    monoFont: '"IBM Plex Mono", monospace',
    radius: "sharp",
    density: "tight",
    surface: "flat",
  },
  {
    id: "ruby",
    name: "红宝石",
    tagline: "血红闪光 · 珠宝橱窗",
    layout: "immersive",
    themeColor: "#1c0508",
    bg: "#1c0508",
    fg: "#ffe4e6",
    muted: "#fb7185",
    accent: "#e11d48",
    accent2: "#f43f5e",
    accentFg: "#fff1f2",
    card: "rgba(225,29,72,0.16)",
    line: "rgba(251,113,133,0.4)",
    danger: "#fda4af",
    font: '"Syne", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "raised",
    wallpaper:
      "radial-gradient(ellipse at 50% 50%, #881337 0%, #1c0508 70%)",
  }, {
    id: "twilight",
    name: "暮色",
    tagline: "靛紫黄昏 · 城市天际",
    layout: "immersive",
    themeColor: "#0f0a1e",
    bg: "#0f0a1e",
    fg: "#e0e7ff",
    muted: "#a5b4fc",
    accent: "#818cf8",
    accent2: "#f472b6",
    accentFg: "#1e1b4b",
    card: "rgba(129,140,248,0.12)",
    line: "rgba(165,180,252,0.28)",
    danger: "#fb7185",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
      "linear-gradient(180deg, #1e1b4b 0%, #312e81 35%, #7c3aed 70%, #db2777 100%)",
  },
  {
    id: "paprika",
    name: "辣椒",
    tagline: "红椒烈焰 · 食欲满格",
    layout: "compact",
    themeColor: "#450a0a",
    bg: "#450a0a",
    fg: "#fef2f2",
    muted: "#fca5a5",
    accent: "#dc2626",
    accent2: "#ea580c",
    accentFg: "#fff",
    card: "rgba(220,38,38,0.18)",
    line: "rgba(248,113,113,0.35)",
    danger: "#fecaca",
    font: '"Bebas Neue", "Syne", system-ui, sans-serif',
    displayFont: '"Bebas Neue", system-ui, sans-serif',
    radius: "sharp",
    density: "tight",
    surface: "raised",
  },
  {
    id: "aqua",
    name: "水色",
    tagline: "泳池青蓝 · 度假清透",
    layout: "side",
    themeColor: "#ecfeff",
    bg: "#ecfeff",
    fg: "#164e63",
    muted: "#22d3ee",
    accent: "#06b6d4",
    accentFg: "#ecfeff",
    card: "#ffffff",
    line: "rgba(6,182,212,0.28)",
    danger: "#e11d48",
    font: '"Outfit", system-ui, sans-serif',
    radius: "round",
    density: "comfy",
    surface: "raised",
    wallpaper: "linear-gradient(180deg, #cffafe 0%, #ecfeff 50%, #f0fdfa 100%)",
  },
  {
    id: "charcoal",
    name: "木炭",
    tagline: "暖灰碳黑 · 壁炉余烬",
    layout: "side",
    themeColor: "#1c1917",
    bg: "#1c1917",
    fg: "#fafaf9",
    muted: "#a8a29e",
    accent: "#f97316",
    accentFg: "#1c1917",
    card: "#292524",
    line: "rgba(249,115,22,0.3)",
    danger: "#fb7185",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "flat",
  },
  {
    id: "orchid",
    name: "兰色",
    tagline: "淡紫花房 · 春日窗台",
    layout: "split",
    themeColor: "#faf5ff",
    bg: "#faf5ff",
    fg: "#581c87",
    muted: "#a855f7",
    accent: "#9333ea",
    accentFg: "#faf5ff",
    card: "#ffffff",
    line: "rgba(147,51,234,0.22)",
    danger: "#e11d48",
    font: '"Playfair Display", Georgia, serif',
    radius: "pill",
    density: "comfy",
    surface: "raised",
  },
  {
    id: "maple",
    name: "枫叶",
    tagline: "秋橙金黄 · 落叶长廊",
    layout: "immersive",
    themeColor: "#431407",
    bg: "#431407",
    fg: "#fff7ed",
    muted: "#fdba74",
    accent: "#ea580c",
    accent2: "#ca8a04",
    accentFg: "#fff7ed",
    card: "rgba(234,88,12,0.16)",
    line: "rgba(251,146,60,0.35)",
    danger: "#fca5a5",
    font: '"Instrument Serif", Georgia, serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
      "radial-gradient(ellipse at 0% 0%, #9a3412 0%, transparent 50%), radial-gradient(ellipse at 100% 100%, #854d0e 0%, transparent 45%), #431407",
  },
  {
    id: "ozone",
    name: "臭氧",
    tagline: "实验室青 · 数据仪表",
    layout: "compact",
    themeColor: "#042f2e",
    bg: "#042f2e",
    fg: "#ccfbf1",
    muted: "#2dd4bf",
    accent: "#14b8a6",
    accentFg: "#042f2e",
    card: "#0f3d3c",
    line: "rgba(45,212,191,0.4)",
    danger: "#f87171",
    font: '"JetBrains Mono", monospace',
    monoFont: '"JetBrains Mono", monospace',
    radius: "sharp",
    density: "tight",
    surface: "outline",
  }, {
    id: "nightclub",
    name: "夜店",
    tagline: "品红黑底 · 迪斯科灯",
    layout: "immersive",
    themeColor: "#0a0010",
    bg: "#0a0010",
    fg: "#fdf4ff",
    muted: "#e879f9",
    accent: "#d946ef",
    accent2: "#22d3ee",
    accentFg: "#4a044e",
    card: "rgba(217,70,239,0.12)",
    line: "rgba(232,121,249,0.4)",
    danger: "#fb7185",
    font: '"Bebas Neue", "Syne", system-ui, sans-serif',
    displayFont: '"Bebas Neue", system-ui, sans-serif',
    radius: "sharp",
    density: "tight",
    surface: "glass",
    wallpaper:
      "radial-gradient(circle at 20% 30%, #86198f 0%, transparent 35%), radial-gradient(circle at 80% 70%, #0e7490 0%, transparent 35%), #0a0010",
  },  {
    id: "navy-gold",
    name: "海军金",
    tagline: "深蓝金饰 · 礼服礼仪",
    layout: "split",
    themeColor: "#0a1628",
    bg: "#0a1628",
    fg: "#f8fafc",
    muted: "#94a3b8",
    accent: "#c9a227",
    accent2: "#e2c35a",
    accentFg: "#1a1200",
    card: "rgba(201,162,39,0.1)",
    line: "rgba(201,162,39,0.35)",
    danger: "#f87171",
    font: '"Playfair Display", Georgia, serif',
    displayFont: '"Playfair Display", Georgia, serif',
    radius: "soft",
    density: "comfy",
    surface: "raised",
    wallpaper:
      "radial-gradient(ellipse at 50% 0%, #1e3a5f 0%, transparent 55%), #0a1628",
  },  {
    id: "dragonfruit",
    name: "火龙果",
    tagline: "洋红紫皮 · 热带果切",
    layout: "side",
    themeColor: "#2d0a1f",
    bg: "#2d0a1f",
    fg: "#fdf2f8",
    muted: "#f9a8d4",
    accent: "#ec4899",
    accent2: "#a855f7",
    accentFg: "#fff",
    card: "rgba(236,72,153,0.14)",
    line: "rgba(244,114,182,0.35)",
    danger: "#fda4af",
    font: '"Syne", system-ui, sans-serif',
    radius: "pill",
    density: "comfy",
    surface: "glass",
    wallpaper:
      "radial-gradient(circle at 90% 10%, #9d174d 0%, transparent 40%), radial-gradient(circle at 10% 90%, #6b21a8 0%, transparent 40%), #2d0a1f",
  },
  {
    id: "clay",
    name: "陶土",
    tagline: "赤陶暖棕 · 手作工房",
    layout: "side",
    themeColor: "#2c1810",
    bg: "#2c1810",
    fg: "#fef3c7",
    muted: "#d6a27a",
    accent: "#c2410c",
    accent2: "#b45309",
    accentFg: "#fff7ed",
    card: "rgba(194,65,12,0.14)",
    line: "rgba(214,162,122,0.3)",
    danger: "#f87171",
    font: '"Outfit", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "raised",
  },
  {
    id: "pixel",
    name: "像素",
    tagline: "8-bit 绿 · 复古掌机",
    layout: "compact",
    themeColor: "#0f1a0f",
    bg: "#0f1a0f",
    fg: "#9bbc0f",
    muted: "#8bac0f",
    accent: "#9bbc0f",
    accentFg: "#0f380f",
    card: "#1a2f1a",
    line: "rgba(155,188,15,0.45)",
    danger: "#e06c75",
    font: '"IBM Plex Mono", monospace',
    monoFont: '"IBM Plex Mono", monospace',
    radius: "sharp",
    density: "tight",
    surface: "outline",
  },  {
    id: "abyss",
    name: "深渊",
    tagline: "至深蓝黑 · 无底静谧",
    layout: "immersive",
    themeColor: "#01040d",
    bg: "#01040d",
    fg: "#c7d2fe",
    muted: "#6366f1",
    accent: "#4f46e5",
    accent2: "#06b6d4",
    accentFg: "#eef2ff",
    card: "rgba(79,70,229,0.12)",
    line: "rgba(99,102,241,0.3)",
    danger: "#f472b6",
    font: '"Space Grotesk", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
      "radial-gradient(ellipse at 50% 120%, #1e1b4b 0%, transparent 50%), #01040d",
  },

  // —— one showcase theme per NEW layout (15) ——
  {
    id: "layout-stack",
    name: "叠峰",
    tagline: "布局·堆叠 · 大封面纵向",
    layout: "stack",
    themeColor: "#0c1222",
    bg: "#0c1222",
    fg: "#e8eefc",
    muted: "#8b9cc7",
    accent: "#60a5fa",
    accentFg: "#0c1222",
    card: "rgba(96,165,250,0.1)",
    line: "rgba(96,165,250,0.28)",
    danger: "#fb7185",
    font: '"Outfit", system-ui, sans-serif',
    radius: "round",
    density: "comfy",
    surface: "glass",
    wallpaper: "linear-gradient(180deg, #152238 0%, #0c1222 100%)",
  },
  {
    id: "layout-theater",
    name: "剧院红",
    tagline: "布局·剧场 · 歌词舞台",
    layout: "theater",
    themeColor: "#1a0508",
    bg: "#1a0508",
    fg: "#ffe4e6",
    muted: "#fb7185",
    accent: "#f43f5e",
    accentFg: "#fff",
    card: "rgba(0,0,0,0.45)",
    line: "rgba(251,113,133,0.35)",
    danger: "#fda4af",
    font: '"Playfair Display", Georgia, serif',
    displayFont: '"Playfair Display", Georgia, serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
  },
  {
    id: "layout-rail",
    name: "轨行",
    tagline: "布局·轨栏 · 侧图标导航",
    layout: "rail",
    themeColor: "#111827",
    bg: "#111827",
    fg: "#f9fafb",
    muted: "#9ca3af",
    accent: "#34d399",
    accentFg: "#064e3b",
    card: "#1f2937",
    line: "#374151",
    danger: "#f87171",
    font: '"Space Grotesk", system-ui, sans-serif',
    radius: "sharp",
    density: "tight",
    surface: "flat",
  },
  {
    id: "layout-magazine",
    name: "刊页",
    tagline: "布局·杂志 · 大标题编辑",
    layout: "magazine",
    themeColor: "#faf7f2",
    bg: "#faf7f2",
    fg: "#1c1917",
    muted: "#78716c",
    accent: "#0f172a",
    accentFg: "#faf7f2",
    card: "#ffffff",
    line: "rgba(28,25,23,0.12)",
    danger: "#b91c1c",
    font: '"Instrument Serif", Georgia, serif',
    displayFont: '"Playfair Display", Georgia, serif',
    radius: "soft",
    density: "comfy",
    surface: "flat",
  },
  {
    id: "layout-card",
    name: "浮卡",
    tagline: "布局·卡片 · 居中悬浮",
    layout: "card",
    themeColor: "#0f172a",
    bg: "#0f172a",
    fg: "#e2e8f0",
    muted: "#94a3b8",
    accent: "#38bdf8",
    accentFg: "#0c4a6e",
    card: "rgba(15,23,42,0.85)",
    line: "rgba(56,189,248,0.3)",
    danger: "#fb7185",
    font: '"Outfit", system-ui, sans-serif',
    radius: "round",
    density: "comfy",
    surface: "glass",
    wallpaper:
      "radial-gradient(ellipse at 50% 0%, #1e3a5f 0%, transparent 55%), #0f172a",
  },
  {
    id: "layout-dock",
    name: "底栏",
    tagline: "布局·Dock · 底部迷你条",
    layout: "dock",
    themeColor: "#0b1020",
    bg: "#0b1020",
    fg: "#e8eefc",
    muted: "#94a3b8",
    accent: "#38bdf8",
    accentFg: "#0c4a6e",
    card: "rgba(15,23,42,0.75)",
    line: "rgba(56,189,248,0.28)",
    danger: "#fb7185",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
  },
  {
    id: "layout-grid",
    name: "宫墙",
    tagline: "布局·宫格 · 封面墙",
    layout: "grid",
    themeColor: "#18181b",
    bg: "#18181b",
    fg: "#fafafa",
    muted: "#a1a1aa",
    accent: "#f472b6",
    accentFg: "#500724",
    card: "#27272a",
    line: "#3f3f46",
    danger: "#fb7185",
    font: '"Syne", system-ui, sans-serif',
    radius: "soft",
    density: "tight",
    surface: "flat",
  },
  {
    id: "layout-strip",
    name: "底线",
    tagline: "布局·底栏 · 列表优先",
    layout: "strip",
    themeColor: "#09090b",
    bg: "#09090b",
    fg: "#fafafa",
    muted: "#71717a",
    accent: "#a3e635",
    accentFg: "#1a2e05",
    card: "#18181b",
    line: "#27272a",
    danger: "#f87171",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "sharp",
    density: "tight",
    surface: "flat",
  },
  {
    id: "layout-poster",
    name: "竖报",
    tagline: "布局·海报 · 全高封面",
    layout: "poster",
    themeColor: "#1c0a0a",
    bg: "#1c0a0a",
    fg: "#fff1f2",
    muted: "#fda4af",
    accent: "#fb7185",
    accentFg: "#4c0519",
    card: "rgba(0,0,0,0.35)",
    line: "rgba(251,113,133,0.3)",
    danger: "#fecdd3",
    font: '"Outfit", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
  },
  {
    id: "layout-focus",
    name: "凝视",
    tagline: "布局·专注 · 只看当前",
    layout: "focus",
    themeColor: "#0a0a0a",
    bg: "#0a0a0a",
    fg: "#f5f5f5",
    muted: "#a3a3a3",
    accent: "#e5e5e5",
    accentFg: "#0a0a0a",
    card: "#171717",
    line: "#262626",
    danger: "#f87171",
    font: '"Space Grotesk", system-ui, sans-serif',
    radius: "pill",
    density: "comfy",
    surface: "flat",
  },
  {
    id: "layout-library",
    name: "索引",
    tagline: "布局·曲库 · 密表浏览",
    layout: "library",
    themeColor: "#f8fafc",
    bg: "#f8fafc",
    fg: "#0f172a",
    muted: "#64748b",
    accent: "#2563eb",
    accentFg: "#eff6ff",
    card: "#ffffff",
    line: "rgba(15,23,42,0.1)",
    danger: "#dc2626",
    font: '"IBM Plex Mono", monospace',
    monoFont: '"IBM Plex Mono", monospace',
    radius: "sharp",
    density: "tight",
    surface: "flat",
  },
  {
    id: "layout-cinematic",
    name: "宽银幕",
    tagline: "布局·电影 · 信箱画幅",
    layout: "cinematic",
    themeColor: "#000000",
    bg: "#000000",
    fg: "#f5f5f4",
    muted: "#a8a29e",
    accent: "#fbbf24",
    accentFg: "#1c1917",
    card: "rgba(0,0,0,0.5)",
    line: "rgba(251,191,36,0.35)",
    danger: "#f87171",
    font: '"Bebas Neue", "Syne", system-ui, sans-serif',
    displayFont: '"Bebas Neue", system-ui, sans-serif',
    radius: "sharp",
    density: "comfy",
    surface: "flat",
  },
  {
    id: "layout-zen",
    name: "留白",
    tagline: "布局·禅 · 极简封面",
    layout: "zen",
    themeColor: "#f5f5f4",
    bg: "#f5f5f4",
    fg: "#1c1917",
    muted: "#78716c",
    accent: "#292524",
    accentFg: "#fafaf9",
    card: "#ffffff",
    line: "rgba(28,25,23,0.08)",
    danger: "#b91c1c",
    font: '"Songti SC", "Instrument Serif", serif',
    radius: "pill",
    density: "comfy",
    surface: "flat",
  },
  {
    id: "layout-console",
    name: "仪表",
    tagline: "布局·控制台 · 三栏面板",
    layout: "console",
    themeColor: "#020617",
    bg: "#020617",
    fg: "#e2e8f0",
    muted: "#64748b",
    accent: "#22d3ee",
    accentFg: "#083344",
    card: "#0f172a",
    line: "rgba(34,211,238,0.35)",
    danger: "#f87171",
    font: '"JetBrains Mono", monospace',
    monoFont: '"JetBrains Mono", monospace',
    radius: "sharp",
    density: "tight",
    surface: "outline",
  },
  {
    id: "layout-sheet",
    name: "抽匣",
    tagline: "布局·抽屉 · 上下分层",
    layout: "sheet",
    themeColor: "#1e1b4b",
    bg: "#1e1b4b",
    fg: "#eef2ff",
    muted: "#a5b4fc",
    accent: "#818cf8",
    accentFg: "#1e1b4b",
    card: "rgba(255,255,255,0.08)",
    line: "rgba(165,180,252,0.3)",
    danger: "#f9a8d4",
    font: '"Outfit", system-ui, sans-serif',
    radius: "round",
    density: "comfy",
    surface: "glass",
  },
  {
    id: "layout-mosaic",
    name: "嵌合",
    tagline: "布局·马赛克 · Bento 拼贴",
    layout: "mosaic",
    themeColor: "#042f2e",
    bg: "#042f2e",
    fg: "#ccfbf1",
    muted: "#5eead4",
    accent: "#2dd4bf",
    accent2: "#f472b6",
    accentFg: "#134e4a",
    card: "rgba(45,212,191,0.12)",
    line: "rgba(94,234,212,0.3)",
    danger: "#fda4af",
    font: '"Syne", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "raised",
    wallpaper:
      "radial-gradient(circle at 100% 0%, #134e4a 0%, transparent 45%), #042f2e",
  },
];

export type SkinId = (typeof THEME_CATALOG)[number]["id"];

export function getTheme(id: string): ThemeTokens {
  return THEME_CATALOG.find((t) => t.id === id) || THEME_CATALOG[0];
}

export function themeToCssVars(t: ThemeTokens): Record<string, string> {
  return {
    "--bg": t.bg,
    "--bg2": t.bg2 || t.bg,
    "--fg": t.fg,
    "--muted": t.muted,
    "--accent": t.accent,
    "--accent2": t.accent2 || t.accent,
    "--accent-fg": t.accentFg,
    "--card": t.card,
    "--line": t.line,
    "--danger": t.danger,
    "--font": t.font,
    "--display-font": t.displayFont || t.font,
    "--mono-font": t.monoFont || t.font,
    // pill = rounded controls (search/tabs still 999 via CSS); panels must NOT be 999
    // or side/imm cards become giant soap-bubbles (樱花/糖果 etc.).
    "--radius":
      t.radius === "sharp"
        ? "2px"
        : t.radius === "soft"
          ? "12px"
          : t.radius === "round"
            ? "18px"
            : "16px",
    "--radius-sm":
      t.radius === "sharp"
        ? "0px"
        : t.radius === "soft"
          ? "8px"
          : t.radius === "round"
            ? "12px"
            : "12px",
    "--radius-lg":
      t.radius === "sharp"
        ? "4px"
        : t.radius === "soft"
          ? "20px"
          : t.radius === "round"
            ? "28px"
            : "24px",
    "--gap": t.density === "tight" ? "6px" : "10px",
    "--pad": t.density === "tight" ? "8px" : "12px",
    "--wallpaper": t.wallpaper || t.bg,
  };
}
