import { LAYOUT_IDS, type SkinLayout } from "./layouts/layout-ids";

export type { SkinLayout };
export { LAYOUT_IDS };

export type ThemeTokens = {
  id: string;
  name: string;
  /** English display name */
  nameEn: string;
  tagline: string;
  /** English tagline */
  taglineEn: string;
  layout: SkinLayout;
  /** browser chrome */
  themeColor: string;
  bg: string;
  bg2?: string;
  fg: string;
  muted: string;
  accent: string;
  accent2?: string;
  accentFg: string;
  card: string;
  line: string;
  danger: string;
  font: string;
  displayFont?: string;
  monoFont?: string;
  radius: "sharp" | "soft" | "round" | "pill";
  density: "comfy" | "tight";
  surface: "glass" | "flat" | "raised" | "outline";
  /** optional CSS background shorthand (gradient etc.) */
  wallpaper?: string;
};

/** 80-ish color + layout showcase themes — CSS vars paint; layout drives structure. */
export const THEME_CATALOG: ThemeTokens[] = [
  {
    id: "aurora",
    name: "极光",
    nameEn: "Aurora",
    tagline: "北境夜空 · 冰蓝柔光",
    taglineEn: "Northern lights · ice-blue glow",
    layout: "side",
    themeColor: "#0a1628",
    bg: "#0a1628",
    fg: "#eaf2ff",
    muted: "#8ea2c0",
    accent: "#5eead4",
    accent2: "#38bdf8",
    accentFg: "#042f2e",
    card: "rgba(60,76,88,0.78)",
    line: "rgba(94,234,212,0.22)",
    danger: "#fda4af",
    font: '"DM Sans", "PingFang SC", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
    "radial-gradient(ellipse 80% 60% at 15% 0%, #164e63 0%, transparent 55%), radial-gradient(ellipse 70% 50% at 90% 10%, #1e3a8a 0%, transparent 50%), #0a1628",
  },
  {
    id: "midnight",
    name: "午夜",
    nameEn: "Midnight",
    tagline: "OLED 纯黑 · 冷静青线",
    taglineEn: "OLED black · cool cyan lines",
    layout: "compact",
    themeColor: "#000000",
    bg: "#000000",
    fg: "#f4f4f5",
    muted: "#b0b0b0",
    accent: "#22d3ee",
    accentFg: "#083344",
    card: "#0a0a0a",
    line: "#27272a",
    danger: "#fb7185",
    font: '"Syne", "DM Sans", system-ui, sans-serif',
    monoFont: '"IBM Plex Mono", ui-monospace, monospace',
    radius: "sharp",
    density: "tight",
    surface: "flat",
  },
  {
    id: "neon",
    name: "霓虹",
    nameEn: "Neon",
    tagline: "赛博夜色 · 紫青灯牌",
    taglineEn: "Cyber night · purple-cyan signs",
    layout: "immersive",
    themeColor: "#0f0518",
    bg: "#0f0518",
    fg: "#faf5ff",
    muted: "#a78bfa",
    accent: "#e879f9",
    accent2: "#22d3ee",
    accentFg: "#3b0764",
    card: "rgba(15,5,24,0.55)",
    line: "rgba(232,121,249,0.35)",
    danger: "#fb7185",
    font: '"Syne", "DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
    "radial-gradient(circle at 75% 15%, #6b21a8 0%, transparent 42%), radial-gradient(circle at 10% 80%, #0e7490 0%, transparent 40%), #0f0518",
  },
  {
    id: "ocean",
    name: "深海",
    nameEn: "Ocean",
    tagline: "远洋靛蓝 · 圆环封面",
    taglineEn: "Deep indigo · ring covers",
    layout: "side",
    themeColor: "#020617",
    bg: "#020617",
    fg: "#e0f2fe",
    muted: "#a8afb8",
    accent: "#38bdf8",
    accentFg: "#0c4a6e",
    card: "rgba(50,60,76,0.78)",
    line: "rgba(56,189,248,0.28)",
    danger: "#fda4af",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "round",
    density: "comfy",
    surface: "glass",
    wallpaper:
    "radial-gradient(ellipse at 50% 120%, #0c4a6e 0%, transparent 55%), linear-gradient(180deg, #020617, #041525)",
  },
  {
    id: "sakura",
    name: "樱花",
    nameEn: "Sakura",
    tagline: "春日柔粉 · 圆润轻盈",
    taglineEn: "Spring pink · soft & rounded",
    layout: "side",
    themeColor: "#fff1f2",
    bg: "#fff1f2",
    fg: "#4c0519",
    muted: "#765668",
    accent: "#f43f5e",
    accentFg: "#0f172a",
    card: "#ffffff",
    line: "#fecdd3",
    danger: "#e11d48",
    font: '"DM Sans", "PingFang SC", system-ui, sans-serif',
    radius: "pill",
    density: "comfy",
    surface: "raised",
    wallpaper: "linear-gradient(165deg, #fff1f2 0%, #ffe4e6 45%, #fdf2f8 100%)",
  },
  {
    id: "terminal",
    name: "终端",
    nameEn: "Terminal",
    tagline: "CRT 绿字 · 等宽指令",
    taglineEn: "CRT green · monospace CLI",
    layout: "compact",
    themeColor: "#050a05",
    bg: "#050a05",
    fg: "#4ade80",
    muted: "#5f8d6f",
    accent: "#86efac",
    accentFg: "#052e16",
    card: "#0a120a",
    line: "#14532d",
    danger: "#f87171",
    font: '"IBM Plex Mono", "SF Mono", ui-monospace, monospace',
    radius: "sharp",
    density: "tight",
    surface: "outline",
  },
  {
    id: "vinyl",
    name: "黑胶",
    nameEn: "Vinyl",
    tagline: "暖棕复古 · 唱片氛围",
    taglineEn: "Warm brown · record-shop vibe",
    layout: "immersive",
    themeColor: "#1a120e",
    bg: "#1a120e",
    fg: "#f5e6d3",
    muted: "#a8a29e",
    accent: "#d4a574",
    accentFg: "#1c1410",
    card: "rgba(28,20,16,0.72)",
    line: "rgba(212,165,116,0.32)",
    danger: "#f87171",
    font: '"DM Sans", system-ui, sans-serif',
    displayFont: '"Instrument Serif", Georgia, serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
    "radial-gradient(circle at 30% 20%, #3d2a1f 0%, transparent 45%), #1a120e",
  },
  {
    id: "swiss",
    name: "瑞士",
    nameEn: "Swiss",
    tagline: "国际主义 · 红白网格",
    taglineEn: "International style · red/white grid",
    layout: "side",
    themeColor: "#ffffff",
    bg: "#ffffff",
    fg: "#111111",
    muted: "#525252",
    accent: "#dc2626",
    accentFg: "#ffffff",
    card: "#fafafa",
    line: "#111111",
    danger: "#b91c1c",
    font: '"Helvetica Neue", Helvetica, Arial, "PingFang SC", sans-serif',
    radius: "sharp",
    density: "tight",
    surface: "outline",
  },
  {
    id: "sunset",
    name: "落日",
    nameEn: "Sunset",
    tagline: "暮色暖橙 · 晚霞渐变",
    taglineEn: "Warm dusk · evening gradient",
    layout: "immersive",
    themeColor: "#1c0a05",
    bg: "#1c0a05",
    fg: "#fff7ed",
    muted: "#bcb4b0",
    accent: "#fb923c",
    accent2: "#f43f5e",
    accentFg: "#1c0a05",
    card: "rgba(67,20,7,0.55)",
    line: "rgba(251,146,60,0.35)",
    danger: "#fb7185",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
    "radial-gradient(ellipse at 50% 100%, #9a3412 0%, transparent 50%), linear-gradient(165deg, #431407, #1c0a05 70%)",
  },
  {
    id: "noir",
    name: "Noir",
    nameEn: "Noir",
    tagline: "黑白电影 · 高对比",
    taglineEn: "B&W cinema · high contrast",
    layout: "compact",
    themeColor: "#0a0a0a",
    bg: "#0a0a0a",
    fg: "#fafafa",
    muted: "#a3a3a3",
    accent: "#fafafa",
    accentFg: "#0a0a0a",
    card: "#141414",
    line: "#404040",
    danger: "#a3a3a3",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "sharp",
    density: "tight",
    surface: "flat",
  },
  {
    id: "lavender",
    name: "薰衣草",
    nameEn: "Lavender",
    tagline: "雾紫柔光 · 安静午后",
    taglineEn: "Misty purple · quiet afternoon",
    layout: "side",
    themeColor: "#1e1b2e",
    bg: "#1e1b2e",
    fg: "#f3e8ff",
    muted: "#c4b5fd",
    accent: "#c084fc",
    accentFg: "#3b0764",
    card: "rgba(81,76,96,0.78)",
    line: "rgba(192,132,252,0.28)",
    danger: "#f9a8d4",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
    "radial-gradient(ellipse at 20% 0%, #4c1d95 0%, transparent 50%), #1e1b2e",
  },
  {
    id: "ember",
    name: "余烬",
    nameEn: "Ember",
    tagline: "暗室炭火 · 深橙余温",
    taglineEn: "Dark charcoal · deep orange embers",
    layout: "immersive",
    themeColor: "#1a100c",
    bg: "#1a100c",
    fg: "#fff1e6",
    muted: "#c4a08a",
    accent: "#f97316",
    accent2: "#fb923c",
    accentFg: "#1c0a05",
    card: "rgba(42, 24, 18, 0.82)",
    line: "rgba(249, 115, 22, 0.32)",
    danger: "#fb7185",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
    "radial-gradient(ellipse at 40% 90%, #7c2d12 0%, transparent 48%), radial-gradient(ellipse at 85% 10%, #431407 0%, transparent 40%), #1a100c",
  },
  {
    id: "arctic",
    name: "极地",
    nameEn: "Arctic",
    tagline: "冰蓝冷调 · 雪白界面",
    taglineEn: "Ice-blue cool · snow-white UI",
    layout: "side",
    themeColor: "#f0f9ff",
    bg: "#f0f9ff",
    fg: "#0c4a6e",
    muted: "#3d6079",
    accent: "#0284c7",
    accentFg: "#f0f9ff",
    card: "#ffffff",
    line: "rgba(2,132,199,0.2)",
    danger: "#e11d48",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "raised",
    wallpaper: "linear-gradient(180deg, #e0f2fe, #f8fafc 60%)",
  },
  {
    id: "grape",
    name: "葡萄",
    nameEn: "Grape",
    tagline: "深紫果香 · 醇厚夜间",
    taglineEn: "Deep purple fruit · rich night",
    layout: "side",
    themeColor: "#1a0b24",
    bg: "#1a0b24",
    fg: "#f3e8ff",
    muted: "#d8b4fe",
    accent: "#a855f7",
    accentFg: "#0f172a",
    card: "rgba(74,59,85,0.78)",
    line: "rgba(168,85,247,0.3)",
    danger: "#f472b6",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "round",
    density: "comfy",
    surface: "glass",
    wallpaper:
    "radial-gradient(ellipse at top, #581c87 0%, #1a0b24 60%)",
  },
  {
    id: "matrix",
    name: "矩阵",
    nameEn: "Matrix",
    tagline: "数据雨 · 深空绿码",
    taglineEn: "Data rain · deep-space green",
    layout: "compact",
    themeColor: "#000800",
    bg: "#000800",
    fg: "#00ff66",
    muted: "#5c876d",
    accent: "#39ff14",
    accentFg: "#001a08",
    card: "#001a08",
    line: "#004d20",
    danger: "#ff4d4d",
    font: '"IBM Plex Mono", ui-monospace, monospace',
    radius: "sharp",
    density: "tight",
    surface: "outline",
  },
  {
    id: "rose-gold",
    name: "玫瑰金",
    nameEn: "Rose Gold",
    tagline: "香槟金属 · 轻奢质感",
    taglineEn: "Champagne metal · light luxury",
    layout: "immersive",
    themeColor: "#1c1214",
    bg: "#1c1214",
    fg: "#fdf2f4",
    muted: "#e7b8be",
    accent: "#e8b4b8",
    accent2: "#d4a574",
    accentFg: "#3f1f24",
    card: "rgba(60,30,36,0.55)",
    line: "rgba(232,180,184,0.3)",
    danger: "#fb7185",
    font: '"Syne", "DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
    "linear-gradient(145deg, #2a161a 0%, #1c1214 50%, #241810 100%)",
  },
  {
    id: "blueprint",
    name: "蓝图",
    nameEn: "Blueprint",
    tagline: "工程图纸 · 精密网格",
    taglineEn: "Engineering draft · precision grid",
    layout: "side",
    themeColor: "#0b1f3a",
    bg: "#0b1f3a",
    fg: "#dbeafe",
    muted: "#a7b2c0",
    accent: "#3b82f6",
    accentFg: "#0f172a",
    card: "rgba(54,73,98,0.78)",
    line: "rgba(96,165,250,0.35)",
    danger: "#f87171",
    font: '"IBM Plex Mono", ui-monospace, monospace',
    radius: "sharp",
    density: "tight",
    surface: "outline",
    wallpaper:
    "linear-gradient(rgba(59,130,246,0.06) 1px, transparent 1px), linear-gradient(90deg, rgba(59,130,246,0.06) 1px, transparent 1px), #0b1f3a",
  },
  {
    id: "honey",
    name: "蜂蜜",
    nameEn: "Honey",
    tagline: "琥珀甜光 · 暖黄日常",
    taglineEn: "Amber sweet light · warm daily",
    layout: "immersive",
    themeColor: "#1a1408",
    bg: "#1a1408",
    fg: "#fffbeb",
    muted: "#bcb9b0",
    accent: "#f59e0b",
    accentFg: "#1c1408",
    card: "rgba(74,65,49,0.78)",
    line: "rgba(245,158,11,0.35)",
    danger: "#f87171",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "round",
    density: "comfy",
    surface: "glass",
    wallpaper:
    "radial-gradient(ellipse at 30% 0%, #78350f 0%, transparent 50%), #1a1408",
  },
  {
    id: "slate",
    name: "岩灰",
    nameEn: "Slate",
    tagline: "现代中性 · 冷静专业",
    taglineEn: "Modern neutral · calm professional",
    layout: "compact",
    themeColor: "#0f172a",
    bg: "#0f172a",
    fg: "#e2e8f0",
    muted: "#94a3b8",
    accent: "#64748b",
    accentFg: "#f8fafc",
    card: "#1e293b",
    line: "#334155",
    danger: "#f87171",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "flat",
  },
  {
    id: "lime",
    name: "青柠",
    nameEn: "Lime",
    tagline: "酸甜高亮 · 运动活力",
    taglineEn: "Zesty highlight · sporty energy",
    layout: "side",
    themeColor: "#0a1405",
    bg: "#0a1405",
    fg: "#ecfccb",
    muted: "#aab29e",
    accent: "#a3e635",
    accentFg: "#1a2e05",
    card: "rgba(60,71,50,0.78)",
    line: "rgba(163,230,53,0.35)",
    danger: "#fb7185",
    font: '"Syne", "DM Sans", system-ui, sans-serif',
    radius: "pill",
    density: "comfy",
    surface: "raised",
    wallpaper:
    "radial-gradient(circle at 80% 20%, #3f6212 0%, transparent 40%), #0a1405",
  },
  {
    id: "copper",
    name: "红铜",
    nameEn: "Copper",
    tagline: "工业金属 · 铜色高光",
    taglineEn: "Industrial metal · copper highlights",
    layout: "immersive",
    themeColor: "#1a100c",
    bg: "#1a100c",
    fg: "#fde8d8",
    muted: "#b6aca6",
    accent: "#c05621",
    accentFg: "#fff7ed",
    card: "rgba(60,30,15,0.55)",
    line: "rgba(192,86,33,0.4)",
    danger: "#f87171",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
  },
  {
    id: "cloud",
    name: "云朵",
    nameEn: "Cloud",
    tagline: "浅灰天空 · 干净轻盈",
    taglineEn: "Light sky gray · clean & airy",
    layout: "side",
    themeColor: "#f8fafc",
    bg: "#f8fafc",
    fg: "#0f172a",
    muted: "#64748b",
    accent: "#0ea5e9",
    accentFg: "#0f172a",
    card: "#ffffff",
    line: "rgba(15,23,42,0.1)",
    danger: "#e11d48",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "raised",
  },
  {
    id: "forest",
    name: "密林",
    nameEn: "Forest",
    tagline: "苔藓深绿 · 林间静谧",
    taglineEn: "Moss deep green · woodland calm",
    layout: "side",
    themeColor: "#0c140f",
    bg: "#0c140f",
    fg: "#dcfce7",
    muted: "#86efac",
    accent: "#22c55e",
    accentFg: "#052e16",
    card: "rgba(49,64,55,0.78)",
    line: "rgba(34,197,94,0.3)",
    danger: "#f87171",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
    "radial-gradient(ellipse at 10% 90%, #14532d 0%, transparent 45%), #0c140f",
  },
  {
    id: "mocha",
    name: "摩卡",
    nameEn: "Mocha",
    tagline: "咖啡厅 · 棕调舒适",
    taglineEn: "Coffee shop · cozy browns",
    layout: "side",
    themeColor: "#211710",
    bg: "#211710",
    fg: "#f5e6d3",
    muted: "#c4a484",
    accent: "#a67c52",
    accentFg: "#1c1410",
    card: "rgba(60,40,28,0.6)",
    line: "rgba(166,124,82,0.35)",
    danger: "#f87171",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
  },
  {
    id: "ice",
    name: "冰晶",
    nameEn: "Ice",
    tagline: "冷玻璃 · 透明质感",
    taglineEn: "Cold glass · translucent feel",
    layout: "side",
    themeColor: "#0c1222",
    bg: "#0c1222",
    fg: "#e2e8f0",
    muted: "#94a3b8",
    accent: "#a5f3fc",
    accentFg: "#083344",
    card: "rgba(70,79,91,0.78)",
    line: "rgba(165,243,252,0.25)",
    danger: "#fda4af",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
    "linear-gradient(160deg, #0f172a 0%, #0c1222 50%, #082f49 100%)",
  },
  {
    id: "crimson",
    name: "绯红",
    nameEn: "Crimson",
    tagline: "剧院红黑 · 戏剧张力",
    taglineEn: "Theatre red-black · drama",
    layout: "immersive",
    themeColor: "#140000",
    bg: "#140000",
    fg: "#fee2e2",
    muted: "#fca5a5",
    accent: "#dc2626",
    accentFg: "#fff",
    card: "rgba(60,0,0,0.55)",
    line: "rgba(220,38,38,0.4)",
    danger: "#f87171",
    font: '"Instrument Serif", Georgia, serif',
    displayFont: '"Instrument Serif", Georgia, serif',
    radius: "sharp",
    density: "comfy",
    surface: "outline",
  },
  {
    id: "moss",
    name: "苔原",
    nameEn: "Moss",
    tagline: "北欧绿灰 · 克制自然",
    taglineEn: "Nordic green-gray · restrained nature",
    layout: "compact",
    themeColor: "#141a16",
    bg: "#141a16",
    fg: "#e7ebe4",
    muted: "#8fa38a",
    accent: "#6b8f71",
    accentFg: "#0f1411",
    card: "#1c241e",
    line: "rgba(107,143,113,0.35)",
    danger: "#e07a5f",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "flat",
  },
  {
    id: "steel",
    name: "钢青",
    nameEn: "Steel",
    tagline: "冷金属 · 工业蓝灰",
    taglineEn: "Cold metal · industrial blue-gray",
    layout: "side",
    themeColor: "#12151a",
    bg: "#12151a",
    fg: "#e8eef5",
    muted: "#8b9bb0",
    accent: "#7c9cbf",
    accentFg: "#0b1220",
    card: "#1a1f27",
    line: "rgba(124,156,191,0.3)",
    danger: "#f87171",
    font: '"IBM Plex Mono", ui-monospace, monospace',
    radius: "sharp",
    density: "tight",
    surface: "flat",
  },
  {
    id: "cosmos",
    name: "星河",
    nameEn: "Cosmos",
    tagline: "深紫太空 · 星尘微光",
    taglineEn: "Deep purple space · stardust",
    layout: "immersive",
    themeColor: "#070714",
    bg: "#070714",
    fg: "#e0e7ff",
    muted: "#a5b4fc",
    accent: "#818cf8",
    accent2: "#c084fc",
    accentFg: "#1e1b4b",
    card: "rgba(30,27,75,0.55)",
    line: "rgba(129,140,248,0.35)",
    danger: "#f9a8d4",
    font: '"Syne", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
    "radial-gradient(ellipse at 20% 30%, #312e81 0%, transparent 40%), radial-gradient(ellipse at 80% 70%, #4c1d95 0%, transparent 35%), #070714",
  },
  {
    id: "magma",
    name: "岩浆",
    nameEn: "Magma",
    tagline: "地火赤橙 · 炽热压迫",
    taglineEn: "Earth fire · fierce heat",
    layout: "immersive",
    themeColor: "#1a0502",
    bg: "#1a0502",
    fg: "#fff7ed",
    muted: "#bbb3af",
    accent: "#f97316",
    accent2: "#ef4444",
    accentFg: "#431407",
    card: "rgba(74,51,44,0.78)",
    line: "rgba(251,146,60,0.35)",
    danger: "#fca5a5",
    font: '"Outfit", "DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
    "radial-gradient(ellipse at 50% 100%, #7c2d12 0%, transparent 50%), radial-gradient(circle at 20% 20%, #9a3412 0%, transparent 40%), #1a0502",
  },
  {
    id: "jade",
    name: "翠玉",
    nameEn: "Jade",
    tagline: "墨绿奢石 · 金边点缀",
    taglineEn: "Luxury green stone · gold edge",
    layout: "side",
    themeColor: "#022c22",
    bg: "#022c22",
    fg: "#ecfdf5",
    muted: "#aebfba",
    accent: "#d4af37",
    accent2: "#34d399",
    accentFg: "#14532d",
    card: "rgba(57,85,71,0.78)",
    line: "rgba(212,175,55,0.35)",
    danger: "#fb7185",
    font: '"Playfair Display", "Songti SC", Georgia, serif',
    displayFont: '"Playfair Display", Georgia, serif',
    radius: "soft",
    density: "comfy",
    surface: "raised",
    wallpaper:
    "radial-gradient(ellipse at 80% 0%, #065f46 0%, transparent 50%), #022c22",
  },
  {
    id: "amethyst",
    name: "紫晶",
    nameEn: "Amethyst",
    tagline: "宝石紫雾 · 柔光玻璃",
    taglineEn: "Gem purple mist · soft glass",
    layout: "side",
    themeColor: "#1e1033",
    bg: "#1e1033",
    fg: "#f5f3ff",
    muted: "#c4b5fd",
    accent: "#a78bfa",
    accent2: "#e879f9",
    accentFg: "#2e1065",
    card: "rgba(79,67,99,0.78)",
    line: "rgba(196,181,253,0.28)",
    danger: "#fb7185",
    font: '"Space Grotesk", system-ui, sans-serif',
    radius: "round",
    density: "comfy",
    surface: "glass",
    wallpaper:
    "radial-gradient(circle at 30% 20%, #5b21b6 0%, transparent 45%), radial-gradient(circle at 90% 80%, #86198f 0%, transparent 40%), #1e1033",
  },
  {
    id: "espresso",
    name: "浓缩",
    nameEn: "Espresso",
    tagline: "咖啡深棕 · 奶油点缀",
    taglineEn: "Deep coffee brown · cream accents",
    layout: "side",
    themeColor: "#1c1410",
    bg: "#1c1410",
    fg: "#faf6f1",
    muted: "#c4a484",
    accent: "#d6a77a",
    accentFg: "#3b2314",
    card: "#2a1f18",
    line: "rgba(214,167,122,0.28)",
    danger: "#f87171",
    font: '"Instrument Serif", Georgia, serif',
    displayFont: '"Instrument Serif", Georgia, serif',
    radius: "soft",
    density: "comfy",
    surface: "raised",
    wallpaper: "linear-gradient(180deg, #2a1f18 0%, #1c1410 100%)",
  },
  {
    id: "graphite",
    name: "石墨",
    nameEn: "Graphite",
    tagline: "工业灰阶 · 冷硬线条",
    taglineEn: "Industrial grayscale · hard lines",
    layout: "compact",
    themeColor: "#18181b",
    bg: "#18181b",
    fg: "#fafafa",
    muted: "#a1a1aa",
    accent: "#e4e4e7",
    accentFg: "#18181b",
    card: "#27272a",
    line: "#3f3f46",
    danger: "#f43f5e",
    font: '"Space Grotesk", system-ui, sans-serif',
    monoFont: '"JetBrains Mono", monospace',
    radius: "sharp",
    density: "tight",
    surface: "flat",
  },
  {
    id: "burgundy",
    name: "勃艮第",
    nameEn: "Burgundy",
    tagline: "酒红丝绒 · 剧院夜晚",
    taglineEn: "Wine velvet · theatre night",
    layout: "immersive",
    themeColor: "#2a0a14",
    bg: "#2a0a14",
    fg: "#fce7f3",
    muted: "#f9a8d4",
    accent: "#e11d48",
    accent2: "#fbbf24",
    accentFg: "#fff1f2",
    card: "rgba(81,48,57,0.78)",
    line: "rgba(244,114,182,0.3)",
    danger: "#fda4af",
    font: '"Playfair Display", Georgia, serif',
    displayFont: '"Playfair Display", Georgia, serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
    "radial-gradient(ellipse at 50% 0%, #881337 0%, transparent 55%), #2a0a14",
  },
  {
    id: "cobalt",
    name: "钴蓝",
    nameEn: "Cobalt",
    tagline: "电气蓝 · 未来面板",
    taglineEn: "Electric blue · futuristic panel",
    layout: "side",
    themeColor: "#020617",
    bg: "#020617",
    fg: "#dbeafe",
    muted: "#a5abb6",
    accent: "#2563eb",
    accent2: "#22d3ee",
    accentFg: "#eff6ff",
    card: "rgba(44,50,70,0.78)",
    line: "rgba(96,165,250,0.35)",
    danger: "#fb7185",
    font: '"Space Grotesk", system-ui, sans-serif',
    radius: "sharp",
    density: "tight",
    surface: "outline",
    wallpaper:
    "linear-gradient(135deg, #020617 0%, #0f172a 40%, #1e3a8a 100%)",
  },
  {
    id: "saffron",
    name: "藏红花",
    nameEn: "Saffron",
    tagline: "金黄香料 · 南亚暖调",
    taglineEn: "Golden spice · South-Asian warmth",
    layout: "immersive",
    themeColor: "#431407",
    bg: "#431407",
    fg: "#fffbeb",
    muted: "#c7b9b0",
    accent: "#f59e0b",
    accent2: "#f97316",
    accentFg: "#451a03",
    card: "rgba(104,65,48,0.78)",
    line: "rgba(252,211,77,0.35)",
    danger: "#fca5a5",
    font: '"Outfit", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "raised",
    wallpaper:
    "radial-gradient(circle at 70% 30%, #b45309 0%, transparent 45%), #431407",
  },
  {
    id: "shadow",
    name: "暗影",
    nameEn: "Shadow",
    tagline: "深紫黑雾 · 低调神秘",
    taglineEn: "Deep purple fog · quiet mystery",
    layout: "compact",
    themeColor: "#0c0a12",
    bg: "#0c0a12",
    fg: "#e2e0ea",
    muted: "#8b87a0",
    accent: "#7c3aed",
    accentFg: "#ede9fe",
    card: "#16131f",
    line: "rgba(124,58,237,0.35)",
    danger: "#f472b6",
    font: '"Syne", system-ui, sans-serif',
    radius: "sharp",
    density: "tight",
    surface: "flat",
  },
  {
    id: "plum",
    name: "梅子",
    nameEn: "Plum",
    tagline: "深梅紫 · 秋日果香",
    taglineEn: "Deep plum · autumn fruit",
    layout: "immersive",
    themeColor: "#1a0b16",
    bg: "#1a0b16",
    fg: "#fce7f3",
    muted: "#e9a8cd",
    accent: "#c026d3",
    accent2: "#db2777",
    accentFg: "#fdf4ff",
    card: "rgba(73,54,71,0.78)",
    line: "rgba(232,121,249,0.3)",
    danger: "#fb7185",
    font: '"Playfair Display", Georgia, serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
    "radial-gradient(circle at 20% 80%, #701a75 0%, transparent 45%), #1a0b16",
  },
  {
    id: "ruby",
    name: "红宝石",
    nameEn: "Ruby",
    tagline: "血红闪光 · 珠宝橱窗",
    taglineEn: "Blood gem flash · jewelry case",
    layout: "immersive",
    themeColor: "#1c0508",
    bg: "#1c0508",
    fg: "#ffe4e6",
    muted: "#b9a9ab",
    accent: "#e11d48",
    accent2: "#f43f5e",
    accentFg: "#fff1f2",
    card: "rgba(71,44,48,0.78)",
    line: "rgba(251,113,133,0.4)",
    danger: "#fda4af",
    font: '"Syne", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "raised",
    wallpaper:
    "radial-gradient(ellipse at 50% 50%, #881337 0%, #1c0508 70%)",
  },
  {
    id: "twilight",
    name: "暮色",
    nameEn: "Twilight",
    tagline: "靛紫黄昏 · 城市天际",
    taglineEn: "Indigo dusk · city skyline",
    layout: "immersive",
    themeColor: "#0f0a1e",
    bg: "#0f0a1e",
    fg: "#e0e7ff",
    muted: "#a5b4fc",
    accent: "#818cf8",
    accent2: "#f472b6",
    accentFg: "#1e1b4b",
    card: "rgba(65,62,82,0.78)",
    line: "rgba(165,180,252,0.28)",
    danger: "#fb7185",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
    "linear-gradient(180deg, #1e1b4b 0%, #312e81 35%, #7c3aed 70%, #db2777 100%)",
  },
  {
    id: "charcoal",
    name: "木炭",
    nameEn: "Charcoal",
    tagline: "暖灰碳黑 · 壁炉余烬",
    taglineEn: "Warm carbon black · hearth embers",
    layout: "side",
    themeColor: "#1c1917",
    bg: "#1c1917",
    fg: "#fafaf9",
    muted: "#a8a29e",
    accent: "#f97316",
    accentFg: "#1c1917",
    card: "#292524",
    line: "rgba(249,115,22,0.3)",
    danger: "#fb7185",
    font: '"DM Sans", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "flat",
  },
  {
    id: "maple",
    name: "枫叶",
    nameEn: "Maple",
    tagline: "秋橙金黄 · 落叶长廊",
    taglineEn: "Autumn orange-gold · leaf walk",
    layout: "immersive",
    themeColor: "#431407",
    bg: "#431407",
    fg: "#fff7ed",
    muted: "#c7b7b0",
    accent: "#ea580c",
    accent2: "#ca8a04",
    accentFg: "#0f172a",
    card: "rgba(100,58,45,0.78)",
    line: "rgba(251,146,60,0.35)",
    danger: "#fca5a5",
    font: '"Instrument Serif", Georgia, serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
    "radial-gradient(ellipse at 0% 0%, #9a3412 0%, transparent 50%), radial-gradient(ellipse at 100% 100%, #854d0e 0%, transparent 45%), #431407",
  },
  {
    id: "nightclub",
    name: "夜店",
    nameEn: "Nightclub",
    tagline: "品红黑底 · 迪斯科灯",
    taglineEn: "Magenta on black · disco lights",
    layout: "immersive",
    themeColor: "#0a0010",
    bg: "#0a0010",
    fg: "#fdf4ff",
    muted: "#b8b2ba",
    accent: "#d946ef",
    accent2: "#22d3ee",
    accentFg: "#4a044e",
    card: "rgba(66,51,72,0.78)",
    line: "rgba(232,121,249,0.4)",
    danger: "#fb7185",
    font: '"Bebas Neue", "Syne", system-ui, sans-serif',
    displayFont: '"Bebas Neue", system-ui, sans-serif',
    radius: "sharp",
    density: "tight",
    surface: "glass",
    wallpaper:
    "radial-gradient(circle at 20% 30%, #86198f 0%, transparent 35%), radial-gradient(circle at 80% 70%, #0e7490 0%, transparent 35%), #0a0010",
  },
  {
    id: "navy-gold",
    name: "海军金",
    nameEn: "Navy Gold",
    tagline: "深蓝金饰 · 礼服礼仪",
    taglineEn: "Deep navy + gold trim · formal",
    layout: "immersive",
    themeColor: "#0a1628",
    bg: "#0a1628",
    fg: "#f8fafc",
    muted: "#94a3b8",
    accent: "#c9a227",
    accent2: "#e2c35a",
    accentFg: "#1a1200",
    card: "rgba(60,67,73,0.78)",
    line: "rgba(201,162,39,0.35)",
    danger: "#f87171",
    font: '"Playfair Display", Georgia, serif',
    displayFont: '"Playfair Display", Georgia, serif',
    radius: "soft",
    density: "comfy",
    surface: "raised",
    wallpaper:
    "radial-gradient(ellipse at 50% 0%, #1e3a5f 0%, transparent 55%), #0a1628",
  },
  {
    id: "clay",
    name: "陶土",
    nameEn: "Clay",
    tagline: "赤陶暖棕 · 手作工房",
    taglineEn: "Terracotta warm brown · studio craft",
    layout: "side",
    themeColor: "#2c1810",
    bg: "#2c1810",
    fg: "#fef3c7",
    muted: "#d6a27a",
    accent: "#c2410c",
    accent2: "#b45309",
    accentFg: "#fff7ed",
    card: "rgba(79,57,49,0.78)",
    line: "rgba(214,162,122,0.3)",
    danger: "#f87171",
    font: '"Outfit", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "raised",
  },
  {
    id: "abyss",
    name: "深渊",
    nameEn: "Abyss",
    tagline: "至深蓝黑 · 无底静谧",
    taglineEn: "Deep blue-black · bottomless calm",
    layout: "immersive",
    themeColor: "#050814",
    bg: "#050814",
    fg: "#e8ecff",
    muted: "#8b95b8",
    accent: "#818cf8",
    accent2: "#22d3ee",
    accentFg: "#0b1020",
    card: "rgba(15, 23, 48, 0.78)",
    line: "rgba(129, 140, 248, 0.28)",
    danger: "#fb7185",
    font: '"Space Grotesk", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "glass",
    wallpaper:
    "radial-gradient(ellipse at 50% 110%, #1e1b4b 0%, transparent 52%), radial-gradient(ellipse at 15% 0%, #0c1a3a 0%, transparent 40%), #050814",
  },
  {
    id: "lattice",
    name: "宫墙",
    nameEn: "Lattice",
    tagline: "粉霓宫格 · 封面墙感",
    taglineEn: "Palace grid · cover-wall feel",
    layout: "immersive",
    themeColor: "#18181b",
    bg: "#18181b",
    fg: "#fafafa",
    muted: "#a1a1aa",
    accent: "#f472b6",
    accentFg: "#500724",
    card: "#27272a",
    line: "#3f3f46",
    danger: "#fb7185",
    font: '"Syne", system-ui, sans-serif',
    radius: "soft",
    density: "tight",
    surface: "flat",
  },
  {
    id: "bento",
    name: "嵌合",
    nameEn: "Bento",
    tagline: "青绿嵌合 · Bento 拼贴感",
    taglineEn: "Teal mosaic · bento collage",
    layout: "immersive",
    themeColor: "#042f2e",
    bg: "#042f2e",
    fg: "#ccfbf1",
    muted: "#9fbab7",
    accent: "#2dd4bf",
    accent2: "#f472b6",
    accentFg: "#134e4a",
    card: "rgba(49,89,87,0.78)",
    line: "rgba(94,234,212,0.3)",
    danger: "#fda4af",
    font: '"Syne", system-ui, sans-serif',
    radius: "soft",
    density: "comfy",
    surface: "raised",
    wallpaper:
      "radial-gradient(circle at 100% 0%, #134e4a 0%, transparent 45%), #042f2e",
  },
  {
    // Only skin on the gallery layout: warm paper instead of the catalog's
    // near-universal dark glass, so the artwork carries the colour.
    id: "atrium",
    name: "中庭",
    nameEn: "Atrium",
    tagline: "暖白纸感 · 画廊三栏",
    taglineEn: "Warm paper · three-pane gallery",
    layout: "gallery",
    themeColor: "#f6f2ea",
    bg: "#f6f2ea",
    bg2: "#efe8db",
    fg: "#1f1b16",
    muted: "#6d6255",
    accent: "#b4531a",
    accent2: "#d98324",
    accentFg: "#fff8f0",
    card: "rgba(255,253,249,0.82)",
    line: "rgba(31,27,22,0.14)",
    danger: "#a8321f",
    font: '"DM Sans", "PingFang SC", system-ui, sans-serif',
    displayFont: '"Instrument Serif", Georgia, serif',
    radius: "soft",
    density: "comfy",
    surface: "raised",
    wallpaper:
      "radial-gradient(ellipse 70% 55% at 12% -5%, #fdf7ec 0%, transparent 60%), radial-gradient(ellipse 60% 45% at 95% 0%, #f2e4d0 0%, transparent 55%), #f6f2ea",
  },
];

export type SkinId = (typeof THEME_CATALOG)[number]["id"];

export function getTheme(id: string): ThemeTokens {
  return THEME_CATALOG.find((t) => t.id === id) || THEME_CATALOG[0];
}

export function themeToCssVars(t: ThemeTokens): Record<string, string> {
  return {
    "--bg": t.bg,
    "--bg2": t.bg2 || t.bg,
    "--fg": t.fg,
    "--muted": t.muted,
    "--accent": t.accent,
    "--accent2": t.accent2 || t.accent,
    "--accent-fg": t.accentFg,
    "--card": t.card,
    "--line": t.line,
    "--danger": t.danger,
    "--font": t.font,
    "--display-font": t.displayFont || t.font,
    "--mono-font": t.monoFont || t.font,
    // pill = rounded controls (search/tabs still 999 via CSS); panels must NOT be 999
    // or side/imm cards become giant soap-bubbles (樱花/糖果 etc.).
    "--radius":
      t.radius === "sharp"
        ? "2px"
        : t.radius === "soft"
          ? "12px"
          : t.radius === "round"
            ? "18px"
            : "16px",
    "--radius-sm":
      t.radius === "sharp"
        ? "0px"
        : t.radius === "soft"
          ? "8px"
          : t.radius === "round"
            ? "12px"
            : "12px",
    "--radius-lg":
      t.radius === "sharp"
        ? "4px"
        : t.radius === "soft"
          ? "20px"
          : t.radius === "round"
            ? "28px"
            : "24px",
    "--gap": t.density === "tight" ? "6px" : "10px",
    "--pad": t.density === "tight" ? "8px" : "12px",
    "--wallpaper": t.wallpaper || t.bg,
  };
}
